Fix all test issues occurring locally that I can at this stage
*Not* all test issues that I'm seeing locally - remaining to be fixed are:

Can't resolve all parameters for BaseService: (?).
(No line of our code specified. Something up with the constructor for this class by the sound of it?)

Can't bind to 'closeOthers' since it isn't a known property of 'ngb-accordion'.
(Issue with sports.component - sounds like we need an import for bootstrap maybe? But I thought that happened automatically (and bootstrap seems fine in the component I created)

Also, though the tests pass, I see red console.error messages for app.component.spec.ts:
console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Cross origin null forbidden

and later (not in red):

console.log src/app/app.component.ts:19
      Call to API Failed: HttpErrorResponse {
        headers: HttpHeaders { normalizedNames: Map {}, lazyUpdate: null, headers: Map {} },
        status: 0,
        statusText: 'Unknown Error',
        url: null,
        ok: false,
        name: 'HttpErrorResponse',
        message: 'Http failure response for (unknown url): 0 Unknown Error',
        error: ProgressEvent { isTrusted: [Getter] } }

Full errors occuring locally for me at:
https://pastebin.com/3rW8aZZz